---
name: Enforce Pull Request has a valid gitmoji prefix
description: This action enforces that a pull request title contains a valid gitmoji prefix

inputs:
    GITHUB_TOKEN:
        description: 'GitHub token'
        required: true

runs:
  using: "composite"
  steps:
    - name: Get all Gitmoji's
      id: gitmojis
      shell: bash
      run: |
           curl -s https://gitmoji.dev/api/gitmojis | jq '.gitmojis[].emoji' > gitmojis.txt
    - name: Check if PR title has a valid gitmoji prefix
      id: check-gitmoji
      shell: bash
      run: |
           gitmojis=$(cat gitmojis.txt)
           gitmoji=$(echo "${{ github.event.pull_request.title }}" | cut -d ' ' -f1)
           if [[ ! $gitmojis == *"$gitmoji"* ]]; then
             echo "Invalid gitmoji prefix in PR title. Please use a valid gitmoji prefix."
             exit 1
           fi
    - name: Failure Comment
      shell: bash
      if: failure()
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT=":x: Invalid gitmoji prefix in PR title. Please use a valid gitmoji prefix."
        GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

    - name: Success Comment
      shell: bash
      if: success()
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT=":white_check_mark: Valid gitmoji prefix in PR title."
        GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"