name: Enforce gitmoji PR
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  gitmoji-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce gitmoji PR title
        uses: georgepstaylor/gitmoji-pr-title-enforcer@add-test-workflow
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
